[project]
name = "arbitrage-commodities"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "matplotlib>=3.9.4",
    "scipy>=1.13.1",
    "statsmodels>=0.14.6",
    "yfinance>=1.1.0",
]
